---
- name: apache installation
  hosts: testservers
  become: true
  tasks:

  - name: update repository index
    yum:
      update_cache: yes 

  - name: install httpd package
    yum:
      name: httpd
      state: latest  
    when: ansible_distribution == "Centos"

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: create index.html
    file:
      path: /var/www/html/index.html
      state: touch
      owner: apache
      group: apache
      mode: '0644'
  
  - name: populate text in index.html
    lineinfile:
      path: /var/www/html/index.html
      line: look at how they massacred my boy

  - name: restart httpd
    service:
     name: httpd
     status: restarted
    when: ansible_distribution == "Centos"

  - name: restart apache2
    service:
     name: apache2
     status: restarted
    when: ansible_distribution == "ubuntu"

